# Generated by Django 5.0.7 on 2024-08-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funeral',
            name='region',
            field=models.CharField(max_length=100),
        ),
    ]
